In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import torch 
from sklearn .preprocessing import StandardScaler

In [2]:
dataset = pd.read_csv("./CarPrice.csv")
labels=dataset["price"]
features=dataset.drop("price",axis=1)
features=pd.get_dummies(features)
nplabels=np.array(labels).reshape(-1,1)
npfeatures=np.array(features)
features=torch.tensor(npfeatures,dtype=torch.float32)
labels=torch.tensor(nplabels,dtype=torch.float32)
features=StandardScaler().fit_transform(features)
features=torch.tensor(npfeatures,dtype=torch.float32)
print(features)


tensor([[  1.0000,   3.0000,  88.6000,  ...,   1.0000,   0.0000,   0.0000],
        [  2.0000,   3.0000,  88.6000,  ...,   1.0000,   0.0000,   0.0000],
        [  3.0000,   1.0000,  94.5000,  ...,   1.0000,   0.0000,   0.0000],
        ...,
        [203.0000,  -1.0000, 109.1000,  ...,   1.0000,   0.0000,   0.0000],
        [204.0000,  -1.0000, 109.1000,  ...,   0.0000,   0.0000,   0.0000],
        [205.0000,  -1.0000, 109.1000,  ...,   1.0000,   0.0000,   0.0000]])


In [3]:
model = torch.nn.Linear(200,205)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0295, -0.0442,  0.0330,  ..., -0.0667, -0.0249, -0.0617],
        [-0.0701, -0.0443, -0.0539,  ..., -0.0028,  0.0464, -0.0129],
        [-0.0049, -0.0539,  0.0490,  ..., -0.0268,  0.0076,  0.0226],
        ...,
        [-0.0651, -0.0644, -0.0137,  ...,  0.0155,  0.0055,  0.0707],
        [-0.0357,  0.0229, -0.0265,  ...,  0.0207,  0.0516, -0.0361],
        [-0.0455,  0.0539,  0.0697,  ...,  0.0039, -0.0101, -0.0659]],
       requires_grad=True)
Parameter containing:
tensor([-0.0167, -0.0578,  0.0251, -0.0458, -0.0490, -0.0443,  0.0043,  0.0429,
        -0.0640,  0.0637,  0.0287, -0.0242, -0.0196,  0.0569, -0.0231, -0.0243,
        -0.0347, -0.0478,  0.0088, -0.0450, -0.0056, -0.0666, -0.0143, -0.0307,
         0.0484,  0.0176, -0.0142, -0.0204,  0.0324, -0.0397,  0.0602, -0.0173,
        -0.0323,  0.0187,  0.0599, -0.0479,  0.0094,  0.0242, -0.0066,  0.0507,
         0.0557,  0.0598,  0.0623, -0.0352,  0.0246, -0.0230, -0.0669,  0.0367,
         0.0067

In [4]:

preds = model(features)
print(preds.shape)

torch.Size([205, 205])


In [5]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)
print(loss)

<ipython-input-5-0863d7043036>:3: UserWarning: Using a target size (torch.Size([205, 1])) that is different to the input size (torch.Size([205, 205])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss  = mse_loss(preds, labels)


tensor(2.3970e+08, grad_fn=<MseLossBackward0>)


In [6]:
loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor([[-1.2880e+04, -1.0064e+02, -1.3099e+04,  ..., -7.9602e+01,
         -4.7240e+00, -5.2763e-01],
        [-1.2527e+04, -9.7760e+01, -1.2758e+04,  ..., -7.7933e+01,
         -4.5691e+00, -5.1051e-01],
        [-1.2793e+04, -1.0008e+02, -1.3018e+04,  ..., -7.9167e+01,
         -4.6903e+00, -5.2316e-01],
        ...,
        [-1.2554e+04, -9.7892e+01, -1.2784e+04,  ..., -7.8104e+01,
         -4.5799e+00, -5.1206e-01],
        [-1.2752e+04, -9.9633e+01, -1.2976e+04,  ..., -7.8995e+01,
         -4.6694e+00, -5.2131e-01],
        [-1.2857e+04, -1.0057e+02, -1.3078e+04,  ..., -7.9468e+01,
         -4.7172e+00, -5.2607e-01]])
tensor([-129.9117, -126.4628, -129.0995, -128.7497, -125.8023, -130.7249,
        -124.8766, -126.9569, -133.4447, -127.9012, -131.4720, -131.9577,
        -129.8208, -131.1360, -129.9306, -129.8802, -127.9858, -131.7840,
        -131.9274, -132.0790, -133.0647, -133.0689, -126.8688, -129.3345,
        -130.4539, -129.5334, -131.7167, -131.0222, -130.0909, -130.6320

In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-9)

optimizer.step()
optimizer.zero_grad()

preds = model(features)
loss = mse_loss(preds, labels)
print(loss)

tensor(2.3958e+08, grad_fn=<MseLossBackward0>)


<ipython-input-7-0f9b07d060bf>:7: UserWarning: Using a target size (torch.Size([205, 1])) that is different to the input size (torch.Size([205, 205])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = mse_loss(preds, labels)


In [8]:
epochs = 1000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%100 == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

<ipython-input-8-138b09389d4f>:4: UserWarning: Using a target size (torch.Size([205, 1])) that is different to the input size (torch.Size([205, 205])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = mse_loss(preds, labels)


tensor(2.2836e+08, grad_fn=<MseLossBackward0>)
tensor(2.1773e+08, grad_fn=<MseLossBackward0>)
tensor(2.0776e+08, grad_fn=<MseLossBackward0>)
tensor(1.9842e+08, grad_fn=<MseLossBackward0>)
tensor(1.8966e+08, grad_fn=<MseLossBackward0>)
tensor(1.8144e+08, grad_fn=<MseLossBackward0>)
tensor(1.7374e+08, grad_fn=<MseLossBackward0>)
tensor(1.6651e+08, grad_fn=<MseLossBackward0>)
tensor(1.5974e+08, grad_fn=<MseLossBackward0>)
tensor(1.5339e+08, grad_fn=<MseLossBackward0>)
