# Concrete price prediction
The data set from the kaggle:https://www.kaggle.com/datasets/maajdl/yeh-concret-data
### imports
-here we import pytorch for gradients and networks<br>
-pandas for data processing<br>
-numpy for numerical python


In [33]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import torch 


### Reading the csv file
-next we will drop the features not relevant to the output, and the label itself<br>-next we are reshaping the labels 
### Convertion
-converting the dataframes into numpy arrays<br>

-converting the arrays into tensors so we can perform ml operations on them


In [34]:
dataset = pd.read_csv("./Concrete.csv")[:500]
feature = np.array(dataset[["cement","slag","flyash","water","superplasticizer","coarseaggregate","fineaggregate","age"]])
label = np.array(dataset['csMPa'])
label=label.reshape(-1,1)
features = torch.tensor(feature, dtype = torch.float32)
labels = torch.tensor(label, dtype = torch.float32)

-printing the weights and bias

In [35]:
model = torch.nn.Linear(8,1)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1765,  0.2099, -0.1583, -0.0441,  0.0653,  0.0292, -0.1170,  0.0864]],
       requires_grad=True)
Parameter containing:
tensor([-0.1801], requires_grad=True)


#### -making the predictions and printing the shape of the predictions

In [36]:
preds = model(features)
print(preds.shape)

torch.Size([500, 1])


### the loss we will use Mean Squared Error - it is simple and most commom loss function

In [37]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)
print(loss)

tensor(3875.1548, grad_fn=<MseLossBackward0>)


-then we will find gradients and optimize the model to reduce loss

In [38]:
loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor([[ -26927.4219,   -3590.7812,  -10596.0400,  -17553.9258,    -956.2229,
         -105479.7344,  -85856.7734,   -4572.9502]])
tensor([-105.3831])


### the optimizer we will use is SGD-(stochastic gradient descent) to update network weights during training

In [39]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.00000001)

optimizer.step()
optimizer.zero_grad()

preds = model(features)
loss = mse_loss(preds, labels)
print(loss)

tensor(3681.7346, grad_fn=<MseLossBackward0>)


#### printing the loss for 100000 epochs

In [40]:


epochs = 100000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%10 == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

tensor(2431.2693, grad_fn=<MseLossBackward0>)
tensor(1708.8723, grad_fn=<MseLossBackward0>)
tensor(1346.3503, grad_fn=<MseLossBackward0>)
tensor(1163.3387, grad_fn=<MseLossBackward0>)
tensor(1069.8746, grad_fn=<MseLossBackward0>)
tensor(1021.0867, grad_fn=<MseLossBackward0>)
tensor(994.5949, grad_fn=<MseLossBackward0>)
tensor(979.2356, grad_fn=<MseLossBackward0>)
tensor(969.4410, grad_fn=<MseLossBackward0>)
tensor(962.4339, grad_fn=<MseLossBackward0>)
tensor(956.8287, grad_fn=<MseLossBackward0>)
tensor(951.9351, grad_fn=<MseLossBackward0>)
tensor(947.4078, grad_fn=<MseLossBackward0>)
tensor(943.0748, grad_fn=<MseLossBackward0>)
tensor(938.8502, grad_fn=<MseLossBackward0>)
tensor(934.6915, grad_fn=<MseLossBackward0>)
tensor(930.5769, grad_fn=<MseLossBackward0>)
tensor(926.4956, grad_fn=<MseLossBackward0>)
tensor(922.4425, grad_fn=<MseLossBackward0>)
tensor(918.4146, grad_fn=<MseLossBackward0>)
tensor(914.4103, grad_fn=<MseLossBackward0>)
tensor(910.4290, grad_fn=<MseLossBackward0>)
tens